### ISSUE TITLE
[Mod Request] Attraction 

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [FnigePython/QuiltPlay#23]
## Link
https://modrinth.com/mod/attraction

## Why it should be added
Attraction is a mod that makes Netherite blocks and Lodestones magnetic, being able to attract anything that's made out of iron (golems, players wearing iron armour) and items!

This would be useful for mob farms for example! There are also Charged Lodestones which work by striking the Lodestone by a lightning strike, so it can be controlled via redstone!

GIFs taken from the mod page: https://imgur.io/Ivr4RaV https://imgur.io/UGcGZ83

**Comment by FnigePython** [comment]
Pretty good mod, accepted
