### ISSUE TITLE
[Mod Request] Engination

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [FnigePython/QuiltPlay#24]
## Link
https://modrinth.com/mod/engination

## Why it should be added
> Adds hundreds of new cosmetic blocks. Blocks belong to "block groups" that can be cycled through easily with sneak+rightclick.
> 
> Adds various gadgets for conventions and modded adventure maps:
> 
> Growable, throwable tomatoes
> Vertical "Launcher" blocks
> Horizontal "Conveyor" blocks
> Landing Pads to eliminate fall damage
> Disappearing Blocks, which become insubstanital when certain conditions are met (such as punching them with your bare hand, or walking on them), and then reappear shortly after.
> Originally written in a mad rush before BTM, and now updated in a mad rush before Modfest, this mod was made to make mod jams and modder conventions more beautiful and easier to get around.

This mod adds many features that seem very useful and neat when it comes to using it in game, and I would like to see this here ^^

**Comment by FnigePython** [comment]
Currently this mod would be a no, this is mostly due to its crafting recipes being very cheap given what you can do with them (Especially the conveyors)

In the future this might get relooked at but no matter what, a lot of the things would become uncraftable or have their recipes slightly changed.
