### ISSUE TITLE
[Mod Request] Sandwichable + Meal API

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [FnigePython/QuiltPlay#25]
## Link(s)
https://modrinth.com/mod/sandwichable
https://modrinth.com/mod/mealapi

## Why it should be added
Sandwichable is a mod that adds sandwiches that can compound food together into non-stacking sandwich items, they additionally can have potions. Sandwichable also adds blocks such as toasters or chopping boards too, and adding MealAPI is recommended by the mod! ^^

**Comment by FnigePython** [comment]
https://github.com/FoundationGames/Sandwichable/issues/147
Resuggest when this is fixed
