### ISSUE TITLE
[Mod Request] Compressed (Blocks) + Compressed Items

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [FnigePython/QuiltPlay#26]
## Link(s)
https://modrinth.com/mod/compressed
https://modrinth.com/mod/compressed-items

## Why it should be added
These mods will allow for items and blocks to be stored easier in large amounts and should be added to aid in early game in my opinion ^^

Also, imagine a 64x compressed block of cobblestone, funni-

**Comment by FnigePython** [comment]
While the mod idea is fine, the lack of modded block/item support along with other stuff means that it wont get added, though something like Extended Drawers and Packages could be a good alternative to this
