### ISSUE TITLE
[Mod Request] Diggus Maximus

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [FnigePython/QuiltPlay#31]
## Link(s)
- [ ] https://www.curseforge.com/minecraft/mc-mods/diggus-maximus

## Describe the mod
> A mod created to make mining veins of the same blocks significantly easier. Simply hold the "excavate" key(bound to ~ by default,configurable) while mining a block and all the connected blocks will be mined as well, saving you the time from mining each individually.
> 
> Diggus Maximus is highly configurable, featuring:
> 
> Automatically picking up the mined blocks
maximum number of blocks to mine
max distance from start block to spread
the ability to excavate with your hand
> 
> * Tool durability
> * Player exhaustion
> * A blacklist/whitelist
> * Auto stopping before tool breaks
> * Support for mining BlockTags
> 
> Diggus Maximus is required to be installed on both the client, and the server. While playing on a server, the server config will override the clients

## Why it should be added
It'd be a lot more convenient and generally nice to collect resources and advance faster if this was added!

**Comment by FnigePython** [comment]
Not now, but this should definitely be a poll that happens sometime later on
