### ISSUE TITLE
[Mod Request] Biomes O' Plenty + TerraBlender

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [FnigePython/QuiltPlay#32]
## Link(s)
- [ ] https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
- [ ] https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric
(TerraBlender is a dependency of Biomes O' Plenty)

## Describe the mod
> Biomes O' Plenty is an expansive biome mod for Minecraft that adds a slew of new, unique biomes to the Overworld and Nether!  To go along with the new biomes, it adds new plants, flowers, trees, building blocks, and much more!

## Why it should be added
Adds a ton of biomes leading to a more rich world!

## Images, gifs etc.
![image](https://user-images.githubusercontent.com/88039945/199745071-8a82ab3b-e95a-4b78-bd9d-bc8137acc57e.png)

**Comment by FnigePython** [comment]
Closing this as this doesnt seem to have a fabric version

**Comment by Mythical-Forest-Collective** [comment]
Ah fair!
