### ISSUE TITLE
[Mod Request] Oh The Biomes You'll Go

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [FnigePython/QuiltPlay#33]
## Link(s)
- [ ]  https://modrinth.com/mod/biomesyougo

## Describe the mod
> Oh The Biomes You'll Go is an exploration and adventure mod designed to take you on a road trip across Minecraft like no other! Explore over 80 magical, realistic, and breathtaking biomes.

## Why it should be added
Adds even more biomes!

## Images, gifs etc.
![image](https://user-images.githubusercontent.com/88039945/199745697-5b4e9d25-54bb-416d-bbdc-b9ed198f0fe8.png)
![image](https://user-images.githubusercontent.com/88039945/199745722-2b81af3c-be6f-4719-97ee-6383c62fd6b5.png)

**Comment by FnigePython** [comment]
Yeah why not
